# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paulo/unb/FSO-2/trab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paulo/unb/FSO-2/trab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo/unb/FSO-2/trab/CMakeFiles /home/paulo/unb/FSO-2/trab//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo/unb/FSO-2/trab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/paulo/unb/FSO-2/trab/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TrabSO

# Build rule for target.
TrabSO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrabSO
.PHONY : TrabSO

# fast build rule for target.
TrabSO/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/build
.PHONY : TrabSO/fast

#=============================================================================
# Target rules for targets named trab

# Build rule for target.
trab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trab
.PHONY : trab

# fast build rule for target.
trab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trab.dir/build.make CMakeFiles/trab.dir/build
.PHONY : trab/fast

src/MemorySpace.o: src/MemorySpace.cpp.o
.PHONY : src/MemorySpace.o

# target to build an object file
src/MemorySpace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemorySpace.cpp.o
.PHONY : src/MemorySpace.cpp.o

src/MemorySpace.i: src/MemorySpace.cpp.i
.PHONY : src/MemorySpace.i

# target to preprocess a source file
src/MemorySpace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemorySpace.cpp.i
.PHONY : src/MemorySpace.cpp.i

src/MemorySpace.s: src/MemorySpace.cpp.s
.PHONY : src/MemorySpace.s

# target to generate assembly for a file
src/MemorySpace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemorySpace.cpp.s
.PHONY : src/MemorySpace.cpp.s

src/MemoryVector.o: src/MemoryVector.cpp.o
.PHONY : src/MemoryVector.o

# target to build an object file
src/MemoryVector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemoryVector.cpp.o
.PHONY : src/MemoryVector.cpp.o

src/MemoryVector.i: src/MemoryVector.cpp.i
.PHONY : src/MemoryVector.i

# target to preprocess a source file
src/MemoryVector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemoryVector.cpp.i
.PHONY : src/MemoryVector.cpp.i

src/MemoryVector.s: src/MemoryVector.cpp.s
.PHONY : src/MemoryVector.s

# target to generate assembly for a file
src/MemoryVector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/MemoryVector.cpp.s
.PHONY : src/MemoryVector.cpp.s

src/Processo.o: src/Processo.cpp.o
.PHONY : src/Processo.o

# target to build an object file
src/Processo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/Processo.cpp.o
.PHONY : src/Processo.cpp.o

src/Processo.i: src/Processo.cpp.i
.PHONY : src/Processo.i

# target to preprocess a source file
src/Processo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/Processo.cpp.i
.PHONY : src/Processo.cpp.i

src/Processo.s: src/Processo.cpp.s
.PHONY : src/Processo.s

# target to generate assembly for a file
src/Processo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/Processo.cpp.s
.PHONY : src/Processo.cpp.s

src/ProcessoManager.o: src/ProcessoManager.cpp.o
.PHONY : src/ProcessoManager.o

# target to build an object file
src/ProcessoManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/ProcessoManager.cpp.o
.PHONY : src/ProcessoManager.cpp.o

src/ProcessoManager.i: src/ProcessoManager.cpp.i
.PHONY : src/ProcessoManager.i

# target to preprocess a source file
src/ProcessoManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/ProcessoManager.cpp.i
.PHONY : src/ProcessoManager.cpp.i

src/ProcessoManager.s: src/ProcessoManager.cpp.s
.PHONY : src/ProcessoManager.s

# target to generate assembly for a file
src/ProcessoManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/ProcessoManager.cpp.s
.PHONY : src/ProcessoManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trab.dir/build.make CMakeFiles/trab.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trab.dir/build.make CMakeFiles/trab.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trab.dir/build.make CMakeFiles/trab.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrabSO.dir/build.make CMakeFiles/TrabSO.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TrabSO"
	@echo "... trab"
	@echo "... src/MemorySpace.o"
	@echo "... src/MemorySpace.i"
	@echo "... src/MemorySpace.s"
	@echo "... src/MemoryVector.o"
	@echo "... src/MemoryVector.i"
	@echo "... src/MemoryVector.s"
	@echo "... src/Processo.o"
	@echo "... src/Processo.i"
	@echo "... src/Processo.s"
	@echo "... src/ProcessoManager.o"
	@echo "... src/ProcessoManager.i"
	@echo "... src/ProcessoManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/paulo/unb/FSO-2/trab/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

